### ISSUE TITLE
add songs through search page

### ISSUE THREAD

**Issue by 0PandaDEV** [Vleerapp/Vleer#13]

**Comment by obvTiger** [comment]
https://wireway.ch/api/musicAPI/search/?q=never%20gonna%20give%20you%20up :)

**Comment by 0PandaDEV** [comment]
.-.

**Comment by jannisfel** [comment]
1. Search a song and get the metadata:
https://wireway.ch/api/musicAPI/search/?q=never%20gonna%20give%20you%20up
2. Get the "url" value starting with /watch?
3. Get https://wireway.ch/api/ytDl/?video={url} Example: https://wireway.ch/api/ytDl/?video=/watch?v=lYBUbBu4W08
# Warning
The download process may take some time. If the download times out (502), just try once more

**Comment by 0PandaDEV** [comment]
ok i will look into this

**Comment by 0PandaDEV** [comment]
finally added this function
